package com.festu.meeting.service.attachment.argument;

import lombok.Builder;
import lombok.Value;


/**
 * Generated by Thanos
 */
@Value
@Builder
public class SearchAttachmentArgument {
    // TODO implement manual
}
