package com.festu.meeting.service.article.argument;

import lombok.Builder;
import lombok.Value;


/**
 * Generated by Thanos
 */
@Value
@Builder
public class SearchArticleArgument {
    // TODO implement manual
}
