package com.festu.meeting.service.article;

import com.festu.meeting.model.Article;
import com.festu.meeting.service.article.argument.CreateArticleArgument;
import com.festu.meeting.service.article.argument.SearchArticleArgument;
import com.festu.meeting.service.article.argument.UpdateArticleArgument;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;

import java.util.List;
import java.util.Optional;
import java.util.UUID;


/**
 * Generated by Thanos
 */
public interface ArticleService {

    Article create(CreateArticleArgument argument);

    Optional<Article> get(UUID id);

    Article getExisting(UUID id);

    List<Article> list(SearchArticleArgument argument, Sort sort);

    Page<Article> page(SearchArticleArgument argument, Pageable pageable);

    Article update(UUID id, UpdateArticleArgument argument);

    void delete(UUID id);
}