package com.festu.meeting.api.attachment.dto;

import lombok.*;

import java.util.UUID;


/**
 * Generated by Thanos
 */
@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class AttachmentDto {

    UUID id;

    String name;

}