package com.festu.meeting.api.attachment.dto;

import lombok.*;


/**
 * Generated by Thanos
 */
@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class CreateAttachmentDto {

    String name;
}