package com.festu.meeting.api.article.mapper;

import com.festu.meeting.api.article.dto.*;
import com.festu.meeting.model.Article;
import com.festu.meeting.service.article.argument.CreateArticleArgument;
import com.festu.meeting.service.article.argument.SearchArticleArgument;
import com.festu.meeting.service.article.argument.UpdateArticleArgument;

import org.mapstruct.Mapper;


/**
 * Generated by Thanos
 */
@Mapper
public interface ArticleMapper {

    ArticleDto toDto(Article entity);

    ArticleListDto toListDto(Article entity);

    CreateArticleArgument toCreateArgument(CreateArticleDto dto);

    UpdateArticleArgument toUpdateArgument(UpdateArticleDto dto);

    SearchArticleArgument toSearchArgument(SearchArticleDto dto);
}