package com.festu.meeting.model;

import lombok.*;

import javax.persistence.Entity;
import java.util.UUID;


/**
 * Generated by Thanos
 */
@Entity
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Article extends BaseEntity {

    String content;

    Integer countDislike;

    Integer countLike;

    String name;

    UUID attachmentId;
}