package com.festu.meeting.model;

import lombok.*;

import javax.persistence.Entity;


/**
 * Generated by Thanos
 */
@Entity
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Attachment extends BaseEntity {

    String name;
}