package com.festu.meeting.model;

import lombok.*;

import javax.persistence.Entity;
import java.time.LocalDateTime;
import java.util.UUID;


/**
 * Generated by Thanos
 */
@Entity
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Notification extends BaseEntity {

    UUID articleId;

    String content;

    LocalDateTime creationDate;

    Boolean read;

    String title;
}