package com.festu.meeting.api.notification.mapper;

import com.festu.meeting.api.notification.dto.*;
import com.festu.meeting.model.Notification;
import com.festu.meeting.service.notification.argument.CreateNotificationArgument;
import com.festu.meeting.service.notification.argument.SearchNotificationArgument;
import com.festu.meeting.service.notification.argument.UpdateNotificationArgument;

import org.mapstruct.Mapper;


/**
 * Generated by Thanos
 */
@Mapper
public interface NotificationMapper {

    NotificationDto toDto(Notification entity);

    NotificationListDto toListDto(Notification entity);

    CreateNotificationArgument toCreateArgument(CreateNotificationDto dto);

    UpdateNotificationArgument toUpdateArgument(UpdateNotificationDto dto);

    SearchNotificationArgument toSearchArgument(SearchNotificationDto dto);
}