package com.festu.meeting.repository;

import com.festu.meeting.model.Notification;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;

import java.util.UUID;


/**
 * Generated by Thanos
 */
public interface NotificationRepository extends JpaRepository<Notification, UUID>, QuerydslPredicateExecutor<Notification> {
}