package com.festu.meeting.api.notification.dto;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


/**
 * Generated by Thanos
 */
@Getter
@Setter
@NoArgsConstructor
public class SearchNotificationDto {
    // TODO implement manual
}