package com.festu.meeting.api.article;

import com.festu.meeting.api.article.dto.*;
import com.festu.meeting.api.article.mapper.ArticleMapper;
import com.festu.meeting.model.Article;
import com.festu.meeting.service.article.ArticleService;
import com.festu.meeting.service.article.argument.SearchArticleArgument;
import com.festu.meeting.service.article.argument.UpdateArticleArgument;
import com.festu.meeting.utls.CollectionDto;

import com.festu.meeting.utls.MapperUtils;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import java.util.List;
import java.util.UUID;

import static org.springframework.http.HttpStatus.CREATED;


/**
 * Generated by Thanos
 */
@RestController
@RequestMapping("article")
@RequiredArgsConstructor
public class ArticleController {

    private final ArticleService service;
    private final ArticleMapper mapper;

    @PostMapping("create")
    @ResponseStatus(CREATED)
    public ArticleDto create(@RequestBody @Valid CreateArticleDto dto) {
        return MapperUtils.getMapper(mapper::toDto)
                          .compose(service::create)
                          .compose(mapper::toCreateArgument)
                          .apply(dto);
    }

    @GetMapping("{id}")
    public ArticleDto get(@PathVariable UUID id) {
        return MapperUtils.getMapper(mapper::toDto)
                          .compose(service::getExisting)
                          .apply(id);
    }

    @GetMapping("list")
    public List<ArticleListDto> list(SearchArticleDto dto, Sort sort) {
        SearchArticleArgument argument = mapper.toSearchArgument(dto);

        List<Article> list = service.list(argument, sort);

        return MapperUtils.mapList(mapper::toListDto, list);
    }

    @GetMapping("page")
    public CollectionDto<ArticleListDto> page(SearchArticleDto dto, Pageable pageable) {
        SearchArticleArgument argument = mapper.toSearchArgument(dto);

        Page<Article> page = service.page(argument, pageable);

        return MapperUtils.mapPage(mapper::toListDto, page);
    }

    @PostMapping("{id}/update")
    public ArticleDto update(@PathVariable UUID id, @RequestBody @Valid UpdateArticleDto dto) {
        UpdateArticleArgument argument = mapper.toUpdateArgument(dto);

        Article entity = service.update(id, argument);

        return mapper.toDto(entity);
    }

    @PostMapping("{id}/delete")
    public void delete(@PathVariable UUID id) {
        service.delete(id);
    }
}