package com.festu.meeting.service.attachment;

import java.util.UUID;
import java.util.List;

import com.festu.meeting.model.Attachment;
import com.festu.meeting.service.attachment.argument.CreateAttachmentArgument;
import com.festu.meeting.service.attachment.argument.SearchAttachmentArgument;
import com.festu.meeting.service.attachment.argument.UpdateAttachmentArgument;
import org.springframework.data.domain.Pageable;

import java.util.Optional;

import org.springframework.data.domain.Sort;
import org.springframework.data.domain.Page;


/**
 * Generated by Thanos
 */
public interface AttachmentService {

    Attachment create(CreateAttachmentArgument argument);

    Optional<Attachment> get(UUID id);

    Attachment getExisting(UUID id);

    List<Attachment> list(SearchAttachmentArgument argument, Sort sort);

    Page<Attachment> page(SearchAttachmentArgument argument, Pageable pageable);

    Attachment update(UUID id, UpdateAttachmentArgument argument);

    void delete(UUID id);
}