package com.festu.meeting.api.attachment.mapper;

import com.festu.meeting.api.attachment.dto.*;
import com.festu.meeting.model.Attachment;
import com.festu.meeting.service.attachment.argument.CreateAttachmentArgument;
import com.festu.meeting.service.attachment.argument.SearchAttachmentArgument;
import com.festu.meeting.service.attachment.argument.UpdateAttachmentArgument;

import org.mapstruct.Mapper;


/**
 * Generated by Thanos
 */
@Mapper
public interface AttachmentMapper {

    AttachmentDto toDto(Attachment entity);

    AttachmentListDto toListDto(Attachment entity);

    CreateAttachmentArgument toCreateArgument(CreateAttachmentDto dto);

    UpdateAttachmentArgument toUpdateArgument(UpdateAttachmentDto dto);

    SearchAttachmentArgument toSearchArgument(SearchAttachmentDto dto);
}