package com.festu.meeting.service.notification.argument;

import lombok.Builder;
import lombok.Value;


/**
 * Generated by Thanos
 */
@Value
@Builder
public class SearchNotificationArgument {
    // TODO implement manual
}
