package com.festu.meeting.service.notification.argument;

import lombok.Builder;
import lombok.Value;

import java.time.LocalDateTime;
import java.util.UUID;


/**
 * Generated by Thanos
 */
@Value
@Builder
public class UpdateNotificationArgument {

    UUID articleId;

    String content;

    LocalDateTime creationDate;

    Boolean read;

    String title;

}
